source 'https://github.com/CocoaPods/Specs.git'
platform:ios,’9.0’
use_frameworks!
targetsArray = ['YaloGame']
targetsArray.each do |t|
    target t do
	pod 'Masonry'
    pod 'AFNetworking'
    pod 'AxcAE_TabBar'
    pod 'FDFullscreenPopGesture'
    pod 'SDCycleScrollView'
    pod 'YYModel'

  end
end
